### ISSUE TITLE
How do I enable Sass

### ISSUE THREAD

**Issue by hackingbeauty** [electrodejs/electrode-archetype-react-app#28]
Hello, I would like to use Sass in my electrode app.

You usually do this by configuring a Sass loader for Webpack.  

How do I do this?  Thanks!

**Comment by ananavati** [comment]
@hackingbeauty thanks for checking out the docs and hope you are liking electrode.

For now the archetypes only support CSS-Modules & Stylus but we are working towards making the archetypes configurable in a plugin way model, here is the associated feature enhancement https://github.com/electrode-io/electrode-archetype-react-app/issues/30

**Comment by khalidsalomao** [comment]
@ananavati Is there a way to at least overwrite the webpack config while the plugin model is not implemented?

**Comment by ananavati** [comment]
@hackingbeauty @khalidsalomao 

we are working on feature to allow extending webpack config which will allow for enabling SASS here is the related feature issue https://github.com/electrode-io/electrode-archetype-react-app/issues/19

**Comment by darkbls** [comment]
Our team thought about that as well, not for the present situation, but for future possibilities. After reading up a bit this was our assumption, if we needed to change for any given css preprocessor. A correct "how to" to this question would also be of interest, so does the following reasoning makes sense as a possible solution?

- clone the base archetype, and have it in your own repo
- add your webpack sass loader customizing the webpack config scripts (i.e. adding https://github.com/jtangelder/sass-loader)
- then have your application use your own archetype instead of the original one
- whenever you need an upgrade carefully merge the original archetype repo into your own
- this would have you customizing your app with new things, without necessarily changing your app's code, just the underneath layer (the archetype).

I have not read all of the archetypes source code yet, but another possible reasoning could be:
to extend the base archetype, add the changes we want, and have our own app use the extended archetype?

**Comment by iamkevingreen** [comment]
@hackingbeauty @khalidsalomao 

You can easily extend the gulpfile to handle this for you, while it's not exactly ideal or the webpack way it's pretty straight forward. I've modified my gulpfile to account for sass and just add the task to my npm command. 

```
require("electrode-archetype-react-app")();

let sass = require("gulp-sass"),
  livereload = require("gulp-livereload"),
  gulp = require("gulp");

gulp.task('sass', function() {

  srcfile = 'sass/app.scss';
  loadPath = 'client/styles/*';
  destdir = 'client/styles';

  gulp.src(srcfile)
  .pipe(sass({
    noCache: true,
    lineNumbers: true,
    loadPath: loadPath,
    quiet: true
  }))
  .pipe(gulp.dest(destdir));

});

gulp.task("watch", function () {
    livereload.listen();

    gulp.watch('sass/**/*.scss', function() {
      gulp.run('sass');
    });

    gulp.watch([
        "client/styles/app.css",
    ], function (event) {
        livereload.changed(event);
    });

});

gulp.task("sass-dev", ["sass", "watch"]);
```

**Comment by jonathanmccracken** [comment]
Is there any update on this from the core team?

**Comment by klaygomes** [comment]
Is it possible use SCSS with eletrode?

**Comment by dustinaleksiuk** [comment]
@klaygomes Some of us have gotten it working, and @jchip has said that if there's enough interest they will consider adding it as a first class feature of Electrode. Check out this thread for some details and solutions: https://github.com/electrode-io/electrode/issues/333#issuecomment-311553600

**Comment by dan3721** [comment]
Is there an ETA on this? We need to make a snap decision whether to pase till Sass is supported or get in there and add support temporarily...

**Comment by jchip** [comment]
electrode repos have been consolidated at https://github.com/electrode-io/electrode
